## Agregar las librerias necesarias para graficar y la funcion sigmoide

In [27]:
import numpy as np
import scipy.special as sigmoid

In [78]:
#creamos una clace para la red neuronal
class neuronalNetwork:
    
    #inicializa la red neuronal
    def __init__(self, inputnodes, hiddennodes, outputnodes, lerningrate):
        self.inodes=inputnodes
        self.hnodes=hiddennodes
        self.onodes=outputnodes
        self.lr=lerningrate
        
        self.wih=np.random.normal(0.0,pow(self.inodes, -0.5),(self.hnodes,self.inodes))
        self.who=np.random.normal(0.0,pow(self.hnodes, -0.5),(self.onodes,self.hnodes))
        
        self.activation_function=lambda x: sigmoid.expit(x)
        pass
        
    #Entrenador de la red
    def query(self,inputs_list):
        inputs=np.array(inputs_list,ndmin=2).T
        
        hiden_inputs=np.dot(self.wih, inputs)
        hiden_outputs= self.activation_function(hiden_inputs)
        
        final_inputs=np.dot(self.who,hiden_outputs)
        final_outputs=self.activation_function(final_inputs)
        
        return final_outputs
        
        pass
    
    #Query de la red
    def train(self, inputs_list, target_list):
        inputs=np.array(inputs_list, ndmin=2).T
        tragets=np.array(target_list, ndmin=2).T
        
        hidden_inputs=np.dot(self.wih, inputs)
        hiden_outputs= self.activation_function(hidden_inputs)
        
        final_inputs=np.dot(self.who,hiden_outputs)
        final_outputs=self.activation_function(final_inputs)
        
        output_errors= tragets- final_outputs
        hidden_errors= np.dot(self.who.T,output_errors)
        
        self.who +=self.lr*np.dot((output_errors*final_outputs*(1.0- final_outputs)),np.transpose(hiden_outputs))
        self.wih +=self.lr*np.dot((hidden_errors*hiden_outputs*(1.0- hiden_outputs)),np.transpose(inputs))
        
        pass


## Hacemos el esqueleto de la red neuronal inicializando los datos 

In [84]:
input_nodes=10
hidden_nodes=5
output_nodes=1

learninrate=0.3

n= neuronalNetwork(input_nodes,hidden_nodes,output_nodes,learninrate)

In [85]:
np.random.seed(123)
input_nodes=np.random.rand(3,10)
input_nodes

array([[ 0.69646919,  0.28613933,  0.22685145,  0.55131477,  0.71946897,
         0.42310646,  0.9807642 ,  0.68482974,  0.4809319 ,  0.39211752],
       [ 0.34317802,  0.72904971,  0.43857224,  0.0596779 ,  0.39804426,
         0.73799541,  0.18249173,  0.17545176,  0.53155137,  0.53182759],
       [ 0.63440096,  0.84943179,  0.72445532,  0.61102351,  0.72244338,
         0.32295891,  0.36178866,  0.22826323,  0.29371405,  0.63097612]])

In [86]:
np.random.seed(100)
output_nodes=np.random.rand(3,1)
output_nodes

array([[ 0.54340494],
       [ 0.27836939],
       [ 0.42451759]])

In [87]:
n.train(input_nodes,output_nodes)

In [89]:
test_nodes=np.random.rand(1,10)

In [90]:
n.query(test_nodes)

array([[ 0.57278115]])